[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[runner]
magicEnabled = false

[client]
caching = true
displayEnabled = true

[theme]
primaryColor = "#6c5ce7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
